### ISSUE TITLE
Stop adding famous people to your repos

### ISSUE THREAD

**Issue by Qix-** [huanglizhuo/kotlin-in-chinese#11]
Please stop adding famous people to your repositories.

请停止加入著名的个人版本库。

<img width="602" alt="screen shot 2016-03-29 at 9 39 49 pm" src="https://cloud.githubusercontent.com/assets/885648/14132105/c2871ab8-f5f6-11e5-81a6-0bbaed323a92.png">

**Comment by huanglizhuo** [comment]
sorry my fault
