### ISSUE TITLE
翻译建议

### ISSUE THREAD

**Issue by gitzxon** [huanglizhuo/kotlin-in-chinese#15]
原文： We cannot assign such a thing to a variable, but we can refer to it by its name. 

原版翻译：如果在 object 关键字后面有个名字，我们不能把它当做表达式了。虽然不能把它赋值给变量，，但可以通过名字赋值。

我觉得这里应该这样翻译：
虽然不能把它赋值给变量，但是我们可以直接通过名字来使用这个类。

**Comment by huanglizhuo** [comment]
要带上链接  不然我不知道是哪个文件的  :sweat:

**Comment by huanglizhuo** [comment]
@gitzxon  带上链接 不然我不知道是哪个文件的 😓

**Comment by gitzxon** [comment]
https://kotlinlang.org/docs/reference/object-declarations.html

**Comment by huanglizhuo** [comment]
fixed
