### ISSUE TITLE
我想借用一下本翻译的内容

### ISSUE THREAD

**Issue by ice1000** [huanglizhuo/kotlin-in-chinese#18]
我有一个Android App，用于编程的学习，我想把本翻译作为该App的远端内容。

请问。。可以。。。吗？

要查看我的App的话请点击[这个链接](https://github.com/ice1000/PlasticApp)

**Comment by huanglizhuo** [comment]
可以 但请保留出处

**Comment by ice1000** [comment]
呃，我写在README里面行吗？App里面我暂时找不到放哪，以后可以在设置里面搞一个。

OK? @huanglizhuo

**Comment by huanglizhuo** [comment]
可以  只要说明出处就行

**Comment by ice1000** [comment]
thx :+1:
