### ISSUE TITLE
Basic-Types.md 下的字符部分官网有修改

### ISSUE THREAD

**Issue by dreamkidd** [huanglizhuo/kotlin-in-chinese#19]
字符由`Char`类型代表。不能直接将他们视作数字。

```
fun check(c: Char) {
  if (c == 1) { // ERROR: 不兼容的类型
    // ...
  }
}
```

字符是由单引号包裹的`'1'`，特殊的字符通过反斜杠`\`转义，下面的字符序列支持转义：`\t`,`\b`,`\n`,`\r`,`\'`,`\"`,`\\`和`\$`。编码任何其他字符，使用 Unicode 转义语法：`\uFF00`。

我们可以将字符显示的转义为`Int`数字：

```
fun decimalDigitValue(c: Char): Int {
  if (c !in '0'..'9')
    throw IllegalArgumentException("Out of range")
  return c.toInt() - '0'.toInt() // 显示转换为数字
}
```

和数值类型一样，需要一个可空引用时，字符会被装箱。特性不会被装箱保留。

**Comment by ice1000** [comment]
感谢您的补充——虽然我不是Contributer。

**Comment by huanglizhuo** [comment]
已更正  thanks  @dreamkidd
