### ISSUE TITLE
可空标识(比如说 Int?) 或者涉及泛型装箱的问题

### ISSUE THREAD

**Issue by guoyibin27** [huanglizhuo/kotlin-in-chinese#20]
看到文章中，基本数据类型里面有关 Int? 装箱的说法，我发现了一个问题，比如  
val a: Int = 100
print (a === a ) //打印 'true'
val boxedA: Int? =a
val anotherBoxedA: Int? = a
print (boxedA === anotherBoxedA ) //注意这里打印的是 'true', 最新版的Kotlin版本
但是如果
val a: Int = 10000
print (a === a ) //打印 'true'
val boxedA: Int? =a
val anotherBoxedA: Int? = a
print (boxedA === anotherBoxedA ) //注意这里打印的是 'false'，

难道Kotlin根据数值进行装箱操作吗？我在官方文档中也没找到相关的说明，不知道你有没有看到？多谢。

**Comment by ice1000** [comment]
我看到这问题两个反应：
第一，你var a = 100好不好，人家会自动推断类型的啊。。。
第二，Int在Kotlin中会被编译成Java中的值类型int，但是Int?会被编译成Integer类的对象。



然后我试了一下，发现127以下的Int属于上面那种情况，128以上属于下面那种，也就是说可能是按照单字节补码来做的优化。
仅为个人猜测。。。

**Comment by sorra** [comment]
-128~127的Integer有缓存，不会重复创建。详见JDK Integer.valueOf(int) 源码

**Comment by ice1000** [comment]
@sorra 感谢 :joy:
