### ISSUE TITLE
##基本类型

### ISSUE THREAD

**Issue by qinsJs** [huanglizhuo/kotlin-in-chinese#28]
这是什么鬼- -，你能不能在##后面加一个空格。。。

**Comment by huanglizhuo** [comment]
@WardenAndroid  之前 gitbook 的 markdown 解析可以不加空格.所以一直没注意
写了一小段 https://github.com/huanglizhuo/kotlin-in-chinese/blob/master/addSpace2Sharp.go
go代码给所有 ## 都加了空格
