### ISSUE TITLE
源码查看地址出错？

### ISSUE THREAD

**Issue by zhuanghongji** [huanglizhuo/kotlin-in-chinese#48]
”本书源码在 [github](https://github.com/huanglizhuo/kotlin-in-chinese)”  
我点击了链接跳转到了 https://github.com/huanglizhuo/kotlin-in-chinese 这个地址  
  
**翻译跟源码在同一个repo下？**
但是我在这个repo下找了全部的目录也没找到源码文件

**Comment by huanglizhuo** [comment]
表示是我的表达有误，本书源码是指的 md 文件，用来生成 gitbook 内容😂
刚把这句话删除了 @zhuanghongji
