### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by WandW** [huanglizhuo/kotlin-in-chinese#49]
在代理属性上面有个println少了个r

**Comment by huanglizhuo** [comment]
thanks for you reminder @WandW   
fixed

**Comment by WandW** [comment]
在代理属性章节 set和get方法是不是有错误，在官方文档里面是setValue 和getValue 并且代码部分有区别。我试过官方的能运行您的出现错误。

**Comment by huanglizhuo** [comment]
是我的锅
这一章节没有跟上最新的 1.1 版本的文档，最新的提交中我已经对照 1.1 的文档修改了翻译.
if you find any other error , please fell free to create issue or PR to notify me. @WandW 
还有不要用您这么客气的词语，有问题尽管开 issue 或者帮忙修正提PR :)
