### ISSUE TITLE
请求转载

### ISSUE THREAD

**Issue by chpengzh** [huanglizhuo/kotlin-in-chinese#54]
我们建立了一个新的社区[Kotlin China](https://kotlin-china.wiki)，请问能否让我们在精品区下，转载该项目下的文章。我们将标明原项目地址和作者，同时期待您的加入。

**Comment by ZQiang94** [comment]
你这个名字成功的引起了我的注意
![image](https://user-images.githubusercontent.com/7663942/27171829-7f652080-51e5-11e7-8851-2a081d46673b.png)
从零到一，算我一个吧。

**Comment by chpengzh** [comment]
ok~ thx

**Comment by huanglizhuo** [comment]
可以

**Comment by huanglizhuo** [comment]
这两天出去旅游 刚看到

**Comment by huanglizhuo** [comment]
最好在说明作者出处之类的地方给个代码contributer链接  有多小伙伴有帮忙过改错 提issue 发pr

**Comment by chpengzh** [comment]
ok
