### ISSUE TITLE
PDF文件异常

### ISSUE THREAD

**Issue by Vicent9920** [huanglizhuo/kotlin-in-chinese#69]
您好，我下载了你们网站的PDF文件，但是下载下来的文件使用PDF.js以及PDFView均不能正常加载，请问是因为你们生成PDF文件的编辑过程加密了还是什么原因呢？（只能正常显示第一页）另外，使用浏览器加载没有任何影响！

**Comment by huanglizhuo** [comment]
@Vicent9920  你是在哪里下载的pdf文件，readme中提供的pdf文件是 gitbook 生成的 ，下载到本地是可以正常阅读，问题可能出在PDF.js以及PDFView上

**Comment by Vicent9920** [comment]
下载地址：https://legacy.gitbook.com/download/pdf/book/huanglizhuo/kotlin-in-chinese
我通过PDFbox解析出了第二页的文本，但是使用PDF.js以及PDFView均不能正常加载，于是乎换了一个几百页的PDF文件，用PDF.js和PDFView也能正常打开，所以我想问的是，都是PDF文件，是不是文件格式是不是有什么区别？

**Comment by Vicent9920** [comment]
我仔细研究了一下，WebView加载pdf.js是因为系统4.4的WebView不支持，高版本（Android使用腾讯X5内核的WebView也可以）加载文件也没有问题了，但是还有一个小建议，PDF文件的第七页是完全空白的，但是网站上面是没有这个页面的，你们看看后期是否可以完善一下这个问题。
