### ISSUE TITLE
泛型 的一个翻译问题

### ISSUE THREAD

**Issue by SeanZom** [huanglizhuo/kotlin-in-chinese#70]
“这个通配符参数 ? extends T 意味着这个方法接受一些 T 类型的子类而非 T 类型本身”

根据官方文档的原文 ：
"The wildcard type argument ? extends E indicates that this method accepts a collection of objects of E or some subtype of E, not just E itself. "

这里应该是：“这个通配符参数 ? extends T 意味着这个方法接受一些 T 类型的子类而不仅仅是 T 类型本身”

**Comment by huanglizhuo** [comment]
fixed
