### ISSUE TITLE
关于LICENSE

### ISSUE THREAD

**Issue by vsTianhao** [huanglizhuo/kotlin-in-chinese#71]
我想copy您的这个项目，把它改一改，加入我的一个文档性质的网站，我这边用的是Apache License 2.0，是否可以呢？

**Comment by huanglizhuo** [comment]
参看 
https://github.com/huanglizhuo/kotlin-in-chinese/issues/18
https://github.com/huanglizhuo/kotlin-in-chinese/issues/54
